### ISSUE TITLE
502 when submitting posts and mail

### ISSUE THREAD

**Issue by nickfausnight-zz** [hubski/hubski-dot-com#5]
I'm ([byonic](https://hubski.com/user/byonic)) getting a 502 when I try to send mail and submit posts.

The mail was to thenewgreen and had the subject and message fields filled out.

The post had no url and the text field filled out, tagged only #bugski - in the first field.

**Comment by nickfausnight-zz** [comment]
Also in the future, are bugs better here or back in bugski - at least when I can post?

**Comment by rob05c** [comment]
Either is fine.

It's another bug from the User SQL conversion. I think I can reproduce it. I'll try to fix it Friday evening. I won't have time before then, sorry.

**Comment by rob05c** [comment]
Should be fixed. (internal changeset 355a94d)
